using iucs.readernest.application.Dto.Billing;
using iucs.readernest.application.Dto.Common;
using iucs.readernest.domain.Enums;

namespace iucs.readernest.application.Services
{
    public interface IBillingService
    {
        Task<IReadOnlyList<PackagePlanDto>> ListPlansAsync(CancellationToken cancellationToken = default);

        /// <summary>Department payment accounts with live transaction stats, for the Payment Gateway Mapping screen.</summary>
        Task<IReadOnlyList<PaymentAccountDto>> ListPaymentAccountsAsync(CancellationToken cancellationToken = default);

        /// <summary>Pins a parent's payments to a specific department account (admin override).</summary>
        Task SetParentPaymentAccountAsync(SavePaymentMappingRequest request, CancellationToken cancellationToken = default);

        /// <summary>Admin edit of a department account's name/provider/ref/active flag.</summary>
        Task<PaymentAccountDto> UpdatePaymentAccountAsync(Guid id, UpdatePaymentAccountRequest request, CancellationToken cancellationToken = default);

        Task<PackagePlanDto> CreatePlanAsync(SavePackagePlanRequest request, CancellationToken cancellationToken = default);

        Task<PackagePlanDto> UpdatePlanAsync(Guid id, SavePackagePlanRequest request, CancellationToken cancellationToken = default);

        /// <summary>Row-by-row. Columns: Name, CourseName (optional), BillingType (Subscription/SessionBased/OneTime),
        /// BillingCycle (Monthly/Quarterly/Yearly/OneTime), Price, SessionsIncluded (optional), IsActive.</summary>
        Task<BulkImportResult> BulkImportPlansAsync(Stream file, string fileName, CancellationToken cancellationToken = default);

        Task<string> ExportPlansCsvAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// Newest-first page of invoices. Paged because this is the one billing table that
        /// grows without bound (every subscription cycle appends a row, forever) and each
        /// row carries four joins for its display names — an unpaged read got slower every
        /// month it ran. <paramref name="pageSize"/> is clamped server-side, so a caller
        /// cannot ask for the whole table back by naming a huge page.
        /// </summary>
        Task<PagedResult<InvoiceDto>> ListInvoicesAsync(
            InvoiceStatus? status,
            Guid? parentProfileId,
            int page,
            int pageSize,
            CancellationToken cancellationToken = default);

        /// <param name="isAutoGenerated">
        /// Internal-only: true when called by BillingBackgroundService for a subscription's
        /// recurring cycle. Deliberately not part of CreateInvoiceRequest so it can never be
        /// set through the public POST /api/invoices body.
        /// </param>
        Task<InvoiceDto> CreateInvoiceAsync(
            CreateInvoiceRequest request,
            CancellationToken cancellationToken = default,
            bool isAutoGenerated = false);

        /// <summary>Renders this invoice as a downloadable "Bill of Supply" PDF.</summary>
        Task<(byte[] Content, string FileName)> GenerateInvoicePdfAsync(Guid id, CancellationToken cancellationToken = default);

        /// <summary>
        /// Ownership-checked equivalent of <see cref="GenerateInvoicePdfAsync"/> for the parent
        /// portal's own invoice download — the same "Bill of Supply" PDF, not a separate document.
        /// </summary>
        Task<(byte[] Content, string FileName)> GenerateParentInvoicePdfAsync(
            Guid parentUserId,
            Guid invoiceId,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Records a successful payment against an invoice (manual entry now;
        /// gateway webhooks call the same path once accounts are provisioned)
        /// and generates the receipt.
        /// </summary>
        Task<InvoiceDto> RecordPaymentAsync(Guid invoiceId, RecordPaymentRequest request, CancellationToken cancellationToken = default);

        /// <summary>
        /// Creates a shareable Pay Now link for an open invoice via the gateway,
        /// routed through the invoice's department payment account.
        /// </summary>
        Task<PaymentLinkDto> CreatePaymentLinkAsync(Guid invoiceId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Parent Pay-Now: for "cash", records a pending cash intent for admin confirmation;
        /// for a gateway key, creates a checkout link plus a pending transaction the webhook settles.
        /// The invoice must belong to the calling parent.
        /// </summary>
        Task<ParentPaymentResultDto> InitiateParentPaymentAsync(
            Guid parentUserId,
            Guid invoiceId,
            InitiateParentPaymentRequest request,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Parent Pay-Now, in-page variant: creates a gateway order + pending transaction and
        /// returns what the browser popup (checkout.js) needs — the payer never leaves the page.
        /// Mode "unavailable" carries the reason when the gateway can't run an inline checkout.
        /// </summary>
        Task<InlineCheckoutDto> StartParentInlineCheckoutAsync(
            Guid parentUserId,
            Guid invoiceId,
            InitiateParentPaymentRequest request,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Settles an inline checkout from the popup's success proof after verifying its
        /// signature with the gateway secret. Returns the refreshed invoice so the UI can
        /// flip to Paid immediately.
        /// </summary>
        Task<InvoiceDto> VerifyParentInlineCheckoutAsync(
            Guid parentUserId,
            Guid invoiceId,
            VerifyInlineCheckoutRequest request,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Gateway webhook settlement: marks the pending transaction with this gateway reference
        /// Success/Failed and, on success, applies the payment to the invoice (receipt, status,
        /// suspension auto-lift). Idempotent — an already-settled reference is a no-op.
        /// </summary>
        Task SettleGatewayTransactionAsync(
            string gatewayReference,
            bool succeeded,
            string? gatewayPaymentId,
            string? failureReason,
            CancellationToken cancellationToken = default);

        // Cash confirmation workflow: a parent's Pay Now "cash" choice records a pending
        // intent; billing staff review it here and confirm once the money is collected.
        Task<IReadOnlyList<CashIntentDto>> ListPendingCashIntentsAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// Confirms a pending cash intent: settles the same transaction row (no duplicate),
        /// generates the receipt and applies the amount to the invoice.
        /// </summary>
        Task<CashIntentDto> ConfirmCashIntentAsync(
            Guid transactionId,
            ConfirmCashIntentRequest request,
            CancellationToken cancellationToken = default);

        /// <summary>Marks a pending cash intent Failed (parent never paid / withdrew).</summary>
        Task RejectCashIntentAsync(
            Guid transactionId,
            RejectCashIntentRequest request,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Pull-based settlement: polls the gateway for each of the invoice's pending checkout
        /// links and settles the invoice if the gateway reports it paid. This is what lets a
        /// completed payment flip the invoice to Paid without waiting on an inbound webhook
        /// (essential on localhost, a safety net in production). Ownership-checked to the parent;
        /// returns the (possibly updated) invoice.
        /// </summary>
        Task<InvoiceDto> ReconcileInvoicePaymentAsync(
            Guid parentUserId,
            Guid invoiceId,
            CancellationToken cancellationToken = default);

        // Renewal tracking workflow: subscriptions drive recurring billing and renew/lapse explicitly
        Task<IReadOnlyList<SubscriptionDto>> ListSubscriptionsAsync(
            SubscriptionStatus? status,
            CancellationToken cancellationToken = default);

        Task<SubscriptionDto> CreateSubscriptionAsync(CreateSubscriptionRequest request, CancellationToken cancellationToken = default);

        /// <summary>Renewal conversion: reactivates a lapsed/cancelled subscription and restarts its billing cycle.</summary>
        Task<SubscriptionDto> RenewSubscriptionAsync(Guid id, CancellationToken cancellationToken = default);

        Task<SubscriptionDto> CancelSubscriptionAsync(Guid id, CancellationToken cancellationToken = default);

        // Fee suspension workflow
        Task<IReadOnlyList<FeeSuspensionDto>> ListSuspensionsAsync(SuspensionStatus? status, CancellationToken cancellationToken = default);

        /// <summary>Manual admin restoration; automatic restoration happens on full payment.</summary>
        Task<FeeSuspensionDto> LiftSuspensionAsync(Guid id, CancellationToken cancellationToken = default);

        /// <summary>Successful payment transactions for one invoice — what a refund can be requested against.</summary>
        Task<IReadOnlyList<PaymentTransactionDto>> ListInvoiceTransactionsAsync(Guid invoiceId, CancellationToken cancellationToken = default);

        // Refund request & tracking workflow
        Task<IReadOnlyList<RefundDto>> ListRefundsAsync(CancellationToken cancellationToken = default);

        Task<RefundDto> RequestRefundAsync(RequestRefundRequest request, CancellationToken cancellationToken = default);

        Task<RefundDto> ReviewRefundAsync(Guid id, ReviewRefundRequest request, CancellationToken cancellationToken = default);
    }
}
