using iucs.readernest.application.Common;
using iucs.readernest.application.Common.Interfaces;
using iucs.readernest.application.Dto.Billing;
using iucs.readernest.application.Services;
using iucs.readernest.domain.Entities.Academics;
using iucs.readernest.domain.Entities.Billing;
using iucs.readernest.domain.Entities.Users;
using iucs.readernest.domain.Enums;
using iucs.readernest.domain.Repository;
using Microsoft.EntityFrameworkCore;

namespace iucs.readernest.api.Services
{
    /// <summary>
    /// Auto billing: on an hourly cycle, generates the next invoice for every active
    /// subscription whose billing date has arrived, advances its next-billing pointer
    /// by the plan's cycle, flags unpaid invoices past their due date as Overdue, and expires
    /// any active subscription whose plan's ValidityDays window has passed.
    /// </summary>
    public class BillingBackgroundService : BackgroundService
    {
        private static readonly TimeSpan Interval = TimeSpan.FromHours(1);

        private readonly IServiceScopeFactory _scopeFactory;
        private readonly ILogger<BillingBackgroundService> _logger;

        public BillingBackgroundService(IServiceScopeFactory scopeFactory, ILogger<BillingBackgroundService> logger)
        {
            _scopeFactory = scopeFactory;
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                try
                {
                    await RunCycleAsync(stoppingToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    _logger.LogError(ex, "Auto billing cycle failed; retrying next interval.");
                }

                await Task.Delay(Interval, stoppingToken);
            }
        }

        private async Task RunCycleAsync(CancellationToken cancellationToken)
        {
            using var scope = _scopeFactory.CreateScope();
            var unitOfWork = scope.ServiceProvider.GetRequiredService<IUnitOfWork>();
            var billingService = scope.ServiceProvider.GetRequiredService<IBillingService>();

            var now = DateTime.UtcNow;

            var dueSubscriptions = await unitOfWork.Repository<Subscription>().Query()
                .Include(s => s.PackagePlan).ThenInclude(p => p.Course)
                .Where(s => s.Status == SubscriptionStatus.Active
                            && s.NextBillingAtUtc != null
                            && s.NextBillingAtUtc <= now)
                .ToListAsync(cancellationToken);

            // Idempotency lookup for the whole due batch in one query instead of an ExistsAsync
            // per subscription. Bounded by the earliest due-instant in the batch, so this never
            // scans the full auto-invoice history — only the periods actually being billed now.
            var dueSubscriptionIds = dueSubscriptions.Select(s => s.Id).ToList();
            var lastAutoInvoiceBySubscription = new Dictionary<Guid, DateTime>();
            if (dueSubscriptions.Count > 0)
            {
                var earliestDue = dueSubscriptions.Min(s => s.NextBillingAtUtc!.Value);
                lastAutoInvoiceBySubscription = await unitOfWork.Repository<Invoice>().Query()
                    .Where(i => i.SubscriptionId != null
                                && dueSubscriptionIds.Contains(i.SubscriptionId.Value)
                                && i.IsAutoGenerated
                                && i.IssuedAtUtc >= earliestDue)
                    .GroupBy(i => i.SubscriptionId!.Value)
                    .Select(g => new { SubscriptionId = g.Key, LatestIssuedAtUtc = g.Max(i => i.IssuedAtUtc) })
                    .ToDictionaryAsync(x => x.SubscriptionId, x => x.LatestIssuedAtUtc, cancellationToken);
            }

            var invoicedCount = 0;
            var failedSubscriptionCount = 0;
            foreach (var subscription in dueSubscriptions)
            {
                // One unbillable subscription must not take the whole cycle down with it.
                // CreateInvoiceAsync throws for ordinary, admin-reachable states — most easily
                // when the department's payment account is deactivated (PUT /api/payment-accounts
                // /{id} with IsActive false), which makes it throw for EVERY subscription in that
                // department. Unguarded, the first one aborted RunCycleAsync entirely, so the
                // overdue sweep, account suspensions, gateway reconciliation and payment reminders
                // below all silently stopped running too — and since the subscription stays due,
                // it threw again on every subsequent hourly run, forever, behind a single log
                // line. Skipping the bad row leaves its NextBillingAtUtc un-advanced, so it is
                // retried next cycle and nothing is silently skipped once the account is fixed.
                try
                {
                    // Idempotency guard: CreateInvoiceAsync commits the invoice with its own
                    // SaveChangesAsync immediately, but the NextBillingAtUtc advance below is only
                    // saved at the end of this cycle. If the process dies or a later save in this
                    // same batch fails in between, the pointer never moves and the next cycle would
                    // otherwise re-bill this exact period. An auto-generated invoice already issued
                    // at/after the due-instant we're about to bill for means this period is already
                    // covered. Scoped to IsAutoGenerated so an unrelated manual/admin invoice on the
                    // same subscription (SubscriptionId is a public field on CreateInvoiceRequest)
                    // can never masquerade as this cycle's invoice and cause a silent skip.
                    var alreadyInvoicedThisPeriod =
                        lastAutoInvoiceBySubscription.TryGetValue(subscription.Id, out var latestIssuedAtUtc)
                        && latestIssuedAtUtc >= subscription.NextBillingAtUtc!.Value;

                    if (!alreadyInvoicedThisPeriod)
                    {
                        await billingService.CreateInvoiceAsync(
                            new CreateInvoiceRequest
                            {
                                ParentProfileId = subscription.ParentProfileId,
                                ChildId = subscription.ChildId,
                                SubscriptionId = subscription.Id,
                                CourseId = subscription.PackagePlan.CourseId,
                                // Route to the department's payment account (dual-gateway requirement);
                                // plans without a course default to Phonics
                                DepartmentId = subscription.PackagePlan.Course?.DepartmentId ?? WellKnownDepartments.Phonics,
                                Amount = subscription.PackagePlan.Price,
                                DueDate = DateOnly.FromDateTime(now.AddDays(7)),
                            },
                            cancellationToken,
                            isAutoGenerated: true);
                        invoicedCount++;
                    }

                    subscription.NextBillingAtUtc = subscription.PackagePlan.BillingCycle switch
                    {
                        BillingCycle.Biweekly => subscription.NextBillingAtUtc!.Value.AddDays(14),
                        BillingCycle.Monthly => subscription.NextBillingAtUtc!.Value.AddMonths(1),
                        BillingCycle.Quarterly => subscription.NextBillingAtUtc!.Value.AddMonths(3),
                        BillingCycle.Yearly => subscription.NextBillingAtUtc!.Value.AddYears(1),
                        _ => null, // one-time plans bill once
                    };
                    unitOfWork.Repository<Subscription>().Update(subscription);
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    failedSubscriptionCount++;
                    _logger.LogError(
                        ex,
                        "Auto billing: subscription {SubscriptionId} could not be invoiced this cycle; "
                        + "its next billing date is unchanged and it will be retried. Continuing with the rest of the batch.",
                        subscription.Id);
                }
            }

            // Fee overdue check: unpaid invoices past their due date turn Overdue.
            // A single UPDATE ... WHERE, rather than loading every past-due invoice into
            // memory to flip one enum and emit an UPDATE per row — the past-due set is
            // unbounded and this job runs hourly forever. ExecuteUpdateAsync bypasses the
            // change tracker, so UpdatedAtUtc is stamped here the way the audit interceptor
            // would have; UpdatedBy is deliberately left alone because this sweep is a system
            // action with no acting user, which is exactly what the interceptor records too.
            var today = DateOnly.FromDateTime(now);
            var overdueCount = await unitOfWork.Repository<Invoice>().ExecuteUpdateAsync(
                i => (i.Status == InvoiceStatus.Pending || i.Status == InvoiceStatus.PartiallyPaid)
                     && i.DueDate < today,
                setters => setters
                    .SetProperty(i => i.Status, InvoiceStatus.Overdue)
                    .SetProperty(i => i.UpdatedAtUtc, now),
                cancellationToken);

            // Validity-days expiry: a plan's ValidityDays computes EndDate once at
            // subscription creation (see BillingService.CreateSubscriptionAsync); this is the
            // only place that date is actually enforced. Bulk update, same pattern as the
            // overdue sweep above -- no need to load full Subscription entities just to flip a
            // status and clear a pointer.
            var expiredCount = await unitOfWork.Repository<Subscription>().ExecuteUpdateAsync(
                s => s.Status == SubscriptionStatus.Active
                     && s.EndDate != null
                     && s.EndDate < today,
                setters => setters
                    .SetProperty(s => s.Status, SubscriptionStatus.Expired)
                    .SetProperty(s => s.NextBillingAtUtc, (DateTime?)null)
                    .SetProperty(s => s.UpdatedAtUtc, now),
                cancellationToken);

            // Commit the subscription pointers before the suspension sweep below queries
            // Invoice via a no-tracking Query() (a direct DB read). The overdue flip above
            // is already committed by its own UPDATE statement, so invoices that turned
            // Overdue in THIS cycle are visible to that query — matching the intent below
            // ("any parent left with an overdue invoice ... gets one") in the same cycle.
            if (dueSubscriptions.Count > 0)
            {
                await unitOfWork.SaveChangesAsync(cancellationToken);
            }

            // Suspension: any (parent, child) pair left with an invoice overdue by at least the
            // configured grace period (Settings → Notifications, BillingSettings) and no active
            // suspension gets one. Grouped by child, not just parent -- an invoice tied to one
            // child (ChildId set) only ever blocks that child; a family-level invoice (ChildId
            // null, e.g. a manually-created one not tied to a subscription) blocks every child
            // on the account. See FeeSuspension's own doc comment.
            var suspendedCount = 0;
            var graceDays = await BillingSettings.GetSuspensionGraceDaysAsync(unitOfWork, cancellationToken);
            var suspensionCutoff = today.AddDays(-graceDays);
            var overdueInvoices = await unitOfWork.Repository<Invoice>().Query()
                .Where(i => i.Status == InvoiceStatus.Overdue && i.DueDate <= suspensionCutoff)
                .Select(i => new { i.ParentProfileId, i.ChildId, i.Id, i.InvoiceNumber })
                .ToListAsync(cancellationToken);

            // One query for every already-suspended parent, instead of an ExistsAsync per
            // overdue (parent, child) pair — that loop scaled its round trips with the size of
            // the overdue book, which is exactly the population that grows when collections are
            // going badly. Loaded once per parent and matched in memory below since a single
            // parent can appear in several groups (one per child).
            var overdueParentIds = overdueInvoices.Select(o => o.ParentProfileId).Distinct().ToList();
            var existingActiveSuspensions = await unitOfWork.Repository<FeeSuspension>().Query()
                .Where(s => s.Status == SuspensionStatus.Active && overdueParentIds.Contains(s.ParentProfileId))
                .Select(s => new { s.ParentProfileId, s.ChildId })
                .ToListAsync(cancellationToken);

            // Caught live: NotificationType.FeeSuspension existed in the enum with zero templates
            // using it -- a parent's access got cut off here with no warning or explanation at
            // all; they'd only find out by trying to access something and being blocked.
            var newlySuspended = new List<(Guid ParentProfileId, string InvoiceNumber)>();
            foreach (var group in overdueInvoices.GroupBy(o => new { o.ParentProfileId, o.ChildId }))
            {
                // An account-wide (ChildId null) suspension already covers this pair regardless
                // of which child it's for; a same-child suspension only covers an exact match.
                var alreadyCovered = existingActiveSuspensions.Any(s =>
                    s.ParentProfileId == group.Key.ParentProfileId && (s.ChildId == null || s.ChildId == group.Key.ChildId));
                if (alreadyCovered)
                {
                    continue;
                }

                var first = group.First();
                await unitOfWork.Repository<FeeSuspension>().AddAsync(
                    new FeeSuspension
                    {
                        ParentProfileId = group.Key.ParentProfileId,
                        ChildId = group.Key.ChildId,
                        InvoiceId = first.Id,
                        Reason = "Automatic suspension: invoice overdue.",
                        SuspendedAtUtc = now,
                    },
                    cancellationToken);
                newlySuspended.Add((group.Key.ParentProfileId, first.InvoiceNumber));
                suspendedCount++;
            }

            if (suspendedCount > 0)
            {
                await unitOfWork.SaveChangesAsync(cancellationToken);

                var notifications = scope.ServiceProvider.GetRequiredService<INotificationService>();
                var suspendedParentIds = newlySuspended.Select(s => s.ParentProfileId).ToList();
                var suspendedParentUsers = await unitOfWork.Repository<ParentProfile>().Query()
                    .Where(p => suspendedParentIds.Contains(p.Id))
                    .Select(p => new { p.Id, p.User })
                    .ToDictionaryAsync(p => p.Id, p => p.User, cancellationToken);
                foreach (var (parentProfileId, invoiceNumber) in newlySuspended)
                {
                    if (!suspendedParentUsers.TryGetValue(parentProfileId, out var user))
                    {
                        continue;
                    }

                    try
                    {
                        await notifications.SendTemplatedEmailAsync(
                            user.Id, user.Email, NotificationType.FeeSuspension, "fee-suspended-parent",
                            new Dictionary<string, string> { ["InvoiceNumber"] = invoiceNumber },
                            cancellationToken);
                    }
                    catch (Exception ex) when (ex is not OperationCanceledException)
                    {
                        _logger.LogWarning(ex, "Fee suspension notice failed for parent {ParentProfileId}; continuing with the rest of the batch.", parentProfileId);
                    }
                }
            }

            if (dueSubscriptions.Count > 0 || overdueCount > 0 || suspendedCount > 0 || expiredCount > 0)
            {
                _logger.LogInformation(
                    "Auto billing: generated {InvoiceCount} invoice(s) ({DueCount} subscription(s) due, {FailedCount} failed), marked {OverdueCount} overdue, suspended {SuspendedCount} account(s), expired {ExpiredCount} subscription(s).",
                    invoicedCount, dueSubscriptions.Count, failedSubscriptionCount, overdueCount, suspendedCount, expiredCount);
            }

            // Pull-based payment settlement: catch any gateway payment whose webhook never
            // arrived (localhost has no public webhook URL; production webhooks can be missed).
            await ReconcilePendingGatewayPaymentsAsync(scope.ServiceProvider, unitOfWork, billingService, now, cancellationToken);

            // Payment reminders go out once a day (the 08:00 UTC cycle), not every hour
            if (now.Hour == 8)
            {
                await SendPaymentRemindersAsync(scope.ServiceProvider, unitOfWork, today, cancellationToken);
            }
        }

        /// <summary>
        /// Polls the gateway for recent pending checkout links and settles the invoice when
        /// the provider reports the link paid. Bounded to the last few days (abandoned links
        /// expire and won't suddenly pay) and a sane cap, so it stays cheap.
        /// </summary>
        private async Task ReconcilePendingGatewayPaymentsAsync(
            IServiceProvider services,
            IUnitOfWork unitOfWork,
            IBillingService billingService,
            DateTime now,
            CancellationToken cancellationToken)
        {
            var since = now.AddDays(-4);
            var pending = await unitOfWork.Repository<PaymentTransaction>().Query()
                .Where(t => t.Status == TransactionStatus.Pending
                            && t.GatewayTransactionId != null
                            && (t.Method == null || t.Method != PaymentMethod.Cash)
                            && t.CreatedAtUtc >= since)
                .OrderBy(t => t.CreatedAtUtc)
                .Take(200)
                .ToListAsync(cancellationToken);

            if (pending.Count == 0)
            {
                return;
            }

            var gateway = services.GetRequiredService<IPaymentGateway>();
            var settled = 0;
            foreach (var transaction in pending)
            {
                try
                {
                    var status = await gateway.GetPaymentStatusAsync(transaction.GatewayTransactionId!, cancellationToken);
                    if (status.State == GatewayPaymentState.Paid)
                    {
                        await billingService.SettleGatewayTransactionAsync(
                            transaction.GatewayTransactionId!, succeeded: true, status.PaymentId, null, cancellationToken);
                        settled++;
                    }
                    else if (status.State == GatewayPaymentState.Failed)
                    {
                        await billingService.SettleGatewayTransactionAsync(
                            transaction.GatewayTransactionId!, succeeded: false, null,
                            "The payment link was cancelled or expired.", cancellationToken);
                    }
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    _logger.LogWarning(ex, "Reconcile failed for gateway reference {Reference}; will retry next cycle.",
                        transaction.GatewayTransactionId);
                }
            }

            if (settled > 0)
            {
                _logger.LogInformation("Payment reconcile: settled {Count} previously-pending gateway payment(s).", settled);
            }
        }

        private async Task SendPaymentRemindersAsync(
            IServiceProvider services,
            IUnitOfWork unitOfWork,
            DateOnly today,
            CancellationToken cancellationToken)
        {
            // Settings → Notifications → "Fee payment reminders" turns this sender off.
            if (!await NotificationToggles.IsEnabledAsync(unitOfWork, NotificationToggles.FeeReminders, cancellationToken))
            {
                return;
            }

            var notifications = services.GetRequiredService<INotificationService>();
            var reminderDays = await BillingSettings.GetReminderDaysBeforeDueAsync(unitOfWork, cancellationToken);
            var reminderWindow = today.AddDays(reminderDays);

            var dueInvoices = await unitOfWork.Repository<Invoice>().Query()
                .Include(i => i.ParentProfile).ThenInclude(p => p.User)
                .Where(i => (i.Status == InvoiceStatus.Pending || i.Status == InvoiceStatus.PartiallyPaid || i.Status == InvoiceStatus.Overdue)
                            && i.DueDate <= reminderWindow)
                .ToListAsync(cancellationToken);

            foreach (var invoice in dueInvoices)
            {
                // One undeliverable address must not cost every later parent in the batch their
                // reminder. This is the 08:00 cycle only, so a lost send waits a full day.
                try
                {
                    var user = invoice.ParentProfile.User;
                    var outstanding = invoice.Amount - invoice.AmountPaid;
                    var templateKey = invoice.Status == InvoiceStatus.Overdue
                        ? "payment-reminder-overdue"
                        : "payment-reminder-due";
                    await notifications.SendTemplatedEmailAsync(
                        user.Id,
                        user.Email,
                        NotificationType.PaymentReminder,
                        templateKey,
                        new Dictionary<string, string>
                        {
                            ["InvoiceNumber"] = invoice.InvoiceNumber,
                            ["DueDate"] = invoice.DueDate.ToString("yyyy-MM-dd"),
                            ["Outstanding"] = outstanding.ToString("0.00"),
                            ["Currency"] = invoice.Currency,
                        },
                        cancellationToken);
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    _logger.LogWarning(
                        ex, "Payment reminder failed for invoice {InvoiceNumber}; continuing with the rest of the batch.",
                        invoice.InvoiceNumber);
                }
            }
        }
    }
}
