using System.ComponentModel.DataAnnotations;
using iucs.readernest.domain.Entities.Academics;
using iucs.readernest.domain.Entities.Common;
using iucs.readernest.domain.Entities.Users;
using iucs.readernest.domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace iucs.readernest.domain.Entities.Billing
{
    /// <summary>
    /// Auto-generated invoice routed to the department's payment account.
    /// Unpaid invoices past DueDate feed the fee-overdue check that triggers suspension.
    /// </summary>
    [Index(nameof(InvoiceNumber), IsUnique = true)]
    [Index(nameof(Status), nameof(DueDate))]
    // GET /api/invoices pages newest-first over IssuedAtUtc (BillingService.ListInvoicesAsync);
    // every current caller fetches unfiltered, so this — not a Status/ParentProfileId
    // composite — is what backs that Skip/Take instead of a full-table sort per page.
    [Index(nameof(IssuedAtUtc))]
    public class Invoice : AuditEntity
    {
        [MaxLength(50)]
        public string InvoiceNumber { get; set; } = null!;

        public Guid ParentProfileId { get; set; }

        public ParentProfile ParentProfile { get; set; } = null!;

        public Guid? ChildId { get; set; }

        public Child? Child { get; set; }

        public Guid? SubscriptionId { get; set; }

        public Subscription? Subscription { get; set; }

        /// <summary>
        /// The course this invoice bills for, when known at creation time (e.g. a
        /// subscription-driven invoice, where the plan's course is in scope). Nullable —
        /// manually-created/admin invoices don't require one. Powers course-wise revenue
        /// reporting; independent of Department, which drives payment-account routing.
        /// </summary>
        public Guid? CourseId { get; set; }

        public Course? Course { get; set; }

        public Guid PaymentAccountId { get; set; }

        public PaymentAccount PaymentAccount { get; set; } = null!;

        public Guid DepartmentId { get; set; }

        public Department Department { get; set; } = null!;

        public decimal Amount { get; set; }

        public decimal AmountPaid { get; set; }

        [MaxLength(3)]
        public string Currency { get; set; } = "INR";

        public InvoiceStatus Status { get; set; } = InvoiceStatus.Pending;

        public DateOnly DueDate { get; set; }

        public DateTime IssuedAtUtc { get; set; }

        public DateTime? PaidAtUtc { get; set; }

        /// <summary>
        /// True only for invoices BillingBackgroundService generated for a subscription's
        /// recurring cycle. Not settable through CreateInvoiceRequest/POST /api/invoices —
        /// it is the idempotency signal that cycle uses to tell "this period is already
        /// billed" apart from an unrelated manual/admin invoice that happens to share the
        /// same SubscriptionId and land on/after the same due date.
        /// </summary>
        public bool IsAutoGenerated { get; set; }

        public ICollection<PaymentTransaction> Transactions { get; set; } = new List<PaymentTransaction>();
    }
}
